[colors.bright]
black = "#0C0C0C"
blue = "#7a7d9a"
cyan = "#9EC3C4"
green = "#9EC49F"
magenta = "#C49EC4"
red = "#C49EA0"
white = "#FAFAFA"
yellow = "#C4C19E"

[colors.dim]
black = "#050505"
blue = "#898cab"
cyan = "#8AABAC"
green = "#8AAC8B"
magenta = "#AC8AAC"
red = "#AC8A8C"
white = "#F0F0F0"
yellow = "#ACA98A"

[colors.normal]
black = "#050505"
blue = "#898cab"
cyan = "#8AABAC"
green = "#8AAC8B"
magenta = "#AC8AAC"
red = "#AC8A8C"
white = "#F0F0F0"
yellow = "#ACA98A"

[colors.primary]
background = "#050505"
# dim_background = "#F0F0F0"
# dim_foreground = "#F0F0F0"
foreground = "#F0F0F0"

[env]
TERM = "xterm-256color"

[font]
size = 10

[window]
dynamic_padding = true
opacity = 1

[window.padding]
x = 6
y = 6
